let lessons = [
  {
    id: 1,
    subject: "Math",
    location: "Dubai",
    price: 120,
    spaces: 5,
    icon: "fa-calculator-simple",
    color: "primary",
  },
  {
    id: 2,
    subject: "English",
    location: "Dubai",
    price: 100,
    spaces: 5,
    icon: "fa-language",
    color: "danger",
  },
  {
    id: 3,
    subject: "Music",
    location: "Dubai",
    price: 150,
    spaces: 5,
    icon: "fa-music",
    color: "purple",
  },
  {
    id: 4,
    subject: "Painting",
    location: "Abu Dhabi",
    price: 130,
    spaces: 5,
    icon: "fa-palette",
    color: "info",
  },
  {
    id: 5,
    subject: "Science",
    location: "Dubai",
    price: 120,
    spaces: 5,
    icon: "fa-flask",
    color: "success",
  },
];