let lessons = [
  {
    id: 1,
    subject: "Math",
    location: "Dubai",
    price: 120,
    spaces: 5,
    icon: "fa-calculator-simple",
    color: "primary",
  },
  {
    id: 2,
    subject: "English",
    location: "Dubai",
    price: 100,
    spaces: 5,
    icon: "fa-language",
    color: "danger",
  },
  {
    id: 3,
    subject: "Music",
    location: "Dubai",
    price: 150,
    spaces: 5,
    icon: "fa-music",
    color: "purple",
  },
  {
    id: 4,
    subject: "Painting",
    location: "Abu Dhabi",
    price: 130,
    spaces: 5,
    icon: "fa-palette",
    color: "info",
  },
  {
    id: 5,
    subject: "Science",
    location: "Dubai",
    price: 120,
    spaces: 5,
    icon: "fa-flask",
    color: "success",
  },
  {
    id: 6,
    subject: "Swimming",
    location: "Sharjah",
    price: 100,
    spaces: 5,
    icon: "fa-person-swimming",
    color: "primary",
  },
  {
    id: 7,
    subject: "Tennis",
    location: "Dubai",
    price: 150,
    spaces: 5,
    icon: "fa-tennis-ball",
    color: "purple",
  },
  {
    id: 8,
    subject: "Dance",
    location: "Abu Dhabi",
    price: 130,
    spaces: 5,
    icon: "fa-child-reaching",
    color: "pink",
  },
  {
    id: 9,
    subject: "Martial Arts",
    location: "Sharjah",
    price: 120,
    spaces: 5,
    icon: "fa-uniform-martial-arts",
    color: "black",
  },
  {
    id: 10,
    subject: "Football",
    location: "Abu Dhabi",
    price: 100,
    spaces: 5,
    icon: "fa-futbol",
    color: "orange",
  },
  {
    id: 11,
    subject: "Golf",
    location: "Dubai",
    price: 180,
    spaces: 5,
    icon: "fa-golf-flag-hole",
    color: "success",
  },
  {
    id: 12,
    subject: "Programming",
    location: "Dubai",
    price: 90,
    spaces: 5,
    icon: "fa-code",
    color: "dark",
  },
  {
    id: 13,
    subject: "Chess",
    location: "Sharjah",
    price: 95,
    spaces: 5,
    icon: "fa-chess",
    color: "primary",
  },
  {
    id: 14,
    subject: "Cooking",
    location: "Sharjah",
    price: 110,
    spaces: 5,
    icon: "fa-pot-food",
    color: "purple",
  },
  {
    id: 15,
    subject: "Photography",
    location: "Abu Dhabi",
    price: 140,
    spaces: 5,
    icon: "fa-camera-retro",
    color: "danger",
  },
];
